--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SVega9848/GlobalToast
build-by-default: true
branches:
  - main
projects:
  GlobalToast:
    path: ""
    icon: "logo.png"
    lint:
      phpstan: false
